version: "3.9"
services:
  mssql:
    build: 
      context: ./db
      args:
        - MSSQL_PASSWORD=P@ssword123

    ports: 
      - 1433:1433
      
    hostname: localhost

  employeemanager:
    build: ./src/EmployeeManager/

    ports: 
      - '80:80'